# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import address.models


class Migration(migrations.Migration):

    dependencies = [
        ('ossi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeder',
            field=models.ForeignKey(to='ossi.Breeder', null=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeder_address',
            field=address.models.AddressField(to='address.Address', null=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeder_affiliation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeder_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeder_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeding_crosses',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeding_differ',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeding_generations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeding_goals',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='breeding_processes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='crop_common_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variety',
            name='crop_latin_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variety',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='variety',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variety',
            name='origin_characteristics',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='origin_parents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='origin_population',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='origin_selection_stabilization',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='origin_single_parent',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='origin_two_or_more',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='sold_commercially',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='stability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variety',
            name='submission_IP',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='submission_IP_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='submission_permission',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='submission_permission_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='submission_signature',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variety',
            name='submission_sole_breeder',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='submission_sole_breeder_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='where_sold_commercially',
            field=models.TextField(),
        ),
    ]
